# main only

name: Integrate

on:
  push:
    branches: [main]

env:
  FORCE_COLOR: 1

jobs:
  _:
    uses: medikoo/github-actions-workflows/.github/workflows/0.12-integrate.yml@main
    secrets:
      USER_GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
